"""initial crane table

Revision ID: 69af4f84e5fc
Revises:
Create Date: 2026-07-18 16:08:35.275296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '69af4f84e5fc'
down_revision: Union[str, Sequence[str], None] = 'a9220af8ab24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crane',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('neighborhood', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lat >= -90 AND lat <= 90', name='ck_crane_lat_range'),
    sa.CheckConstraint('lng >= -180 AND lng <= 180', name='ck_crane_lng_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cranes_location', 'crane', ['location'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cranes_location', table_name='crane', postgresql_using='gist')
    op.drop_table('crane')
    # ### end Alembic commands ###
