"""Create OutboxJob table

Revision ID: 89fe23b2ed7d
Revises: 42da8c9cd521
Create Date: 2026-08-07 16:50:01.950703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89fe23b2ed7d'
down_revision: Union[str, Sequence[str], None] = '42da8c9cd521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.Enum('delete', name='job_operation'), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outbox_job')
    # ### end Alembic commands ###
